### ISSUE TITLE
first() returns and array instead of stdClass object

### ISSUE THREAD

**Issue by xparthxvorax** [jenssegers/laravel-mongodb#1059]
Hello,

I have setup two fresh Laravel 5.3 with different databases. One with MongoDB(using this package) and another with MySQL.

I have run this simple code on both setup:

```
$user = DB::table('users')->first();
dd($user);
```

For above code, Laravel with MySQL returns **stdClass object** whereas Laravel with MongoDB returns **an array**  .

Why is that? Is there any way that I can make it same as Laravel MySQL i.e **stdClass object**?

Due to this different return type issue, I'm not able to use another package with Laravel MongoDB setup.

Any help would be appreciated.

Thanks,
Parth vora

**Comment by xparthx** [comment]
Hey,

Any update on this? By the way my question has nothing to do with any relationship.

Thanks

**Comment by xparthx** [comment]
@jenssegers 

Can you please give some reply to this issue?

**Comment by majuansari** [comment]
Any update on this ?

**Comment by DMNSteve** [comment]
Can you not change the implementation of the package that is trying to use the result of `$user = DB::table('users')->first();` and in your own implementation cast the result as an object?

**Comment by ziadoz** [comment]
This also causes issues with Laravel Passport, as certain parts of it use the database connection directly, rather than using Eloquent models (which can easily be copied and swapped out in a service provider): https://github.com/laravel/passport/blob/610b2ea158ae840a656a4e7f1518d3c6b80f0639/src/Bridge/RefreshTokenRepository.php#L80
