### ISSUE TITLE
MongoDB models relationships in Laravel

### ISSUE THREAD

**Issue by sizerm** [jenssegers/laravel-mongodb#1142]
this is **Post** model data:

    {
	   "_id" : ObjectId("58bb1293534e2028d0006f33"),
	   "body" : "Some body",
	   "comments" : [
		   {
			  "commentID" : "58bb115c534e2028d0006f2d"
		   },
		   {
		   	  "commentID" : "58bb1153534e2028d0006f2c"
		   }
	    ]
    }
this is **Comment** model data:

    {
       "_id" : ObjectId("58bb1153534e2028d0006f2c"),
	   "message" : "Some Message"
    },

    {
       "_id" : ObjectId("58bb115c534e2028d0006f2d"),
 	   "message" : "Another Message"
    }
how to set relationship between these models by jenssegers-mongodb package?

**Comment by benargo** [comment]
Hey @sizerm,

This package utilises Eloquent from Laravel, so just follow the documentation on [defining Eloquent Relationships](https://laravel.com/docs/master/eloquent-relationships#one-to-one).

For example:

````
<?php

namespace App;

use Jenssegers\Mongodb\Eloquent\Model as Eloquent;

class User extends Eloquent
{
    /**
     * Get the phone record associated with the user.
     */
    public function phone()
    {
        return $this->hasOne('App\Phone');
    }
}

````

Since MongoDB also supports embedded documents, you can also utilise the package-specific `embedsOne` and `embedsMany` relationships. See the [package documentation](https://github.com/jenssegers/laravel-mongodb#relations).

**Comment by Marcoslp** [comment]
Hello, 

 return $this->hasOne('App\Comment');

it does not working for me. 

I've got:

=> null

**Comment by benargo** [comment]
Can you provide a little more context? It would be useful to see the whole class.

However, you're probably better off asking this on [Stack Overflow](https://stackoverflow.com/) in the first instance, since there's a high probability this isn't an issue with this particular package.

@jenssegers I suggest you close this issue.

**Comment by tahniya** [comment]
post and comment relationships in laravel solved complete
