### ISSUE TITLE
Model properties are not cleared on changing database connection and run another query

### ISSUE THREAD

**Issue by koAndy** [jenssegers/laravel-mongodb#1554]
I have a model with this static function:
```
Class Trigger {
....
public static function onCustomer(User $customer)
{
        config(['database.connections.' . $customer->server . '.database' => $customer->database]);
        return self::on($customer->server);
}
}
```

If I do this:

`$result = Trigger::onCustomer(User::find('573072804d358b06308b4567'))->get()`

it will return a collection with 2 objects - which is correct!

Then if I do this:
`$result = Trigger::onCustomer(User::find('598e003a1736736644debbc7'))->get()`

it will return the same collection as above, but user 598e003a1736736644debbc7 does not have any records in database.

If I close php artisan tinker and run second command again it will return empty collection. Which is correct. Afterwards if I run the first command written above, it will return empty collection, even if it has 2 objects in it.

Even if I run unset($result) or $result = null and run command again it will not bring correct result.

How can I proper destroy the variable or Trigger class object so at a second run it will bring correct results?

**Comment by ollieread** [comment]
@koAndy This isn't a problem with this package. The problem is that you're changing the config dynamically, but the connection instance still exists. You have to force the connection to reconnect to load the new config.

Also, as a side note, there are nicer ways to achieve this. I have a multitenancy package and I handle it like so;

- I have a separate db config in the config file called `multitenancy`
- I then extend the db manager with something to identify the database name (https://github.com/ollieread/multitenancy/blob/master/src/ServiceProvider.php#L64)
- I have a manager class that stores the current tenant
- On setting the tenant, I call the reconnect method `app(DatabaseManager::class)->connection('multitenancy')->reconnect()`

**Comment by koAndy** [comment]
You are completely right. Debuging it for a few hours, just now I realized that  the connection must be remade!

Thanks a lot!
