### ISSUE TITLE
_id sometimes saved as string sometimes as MongoDB\BSON\ObjectId

### ISSUE THREAD

**Issue by aconital** [jenssegers/laravel-mongodb#1674]
I have a weird situation in my mongodb. When I fetch my rows, some of the rows (earlier ones) are saved with `_id` as an object like this `_id: MongoDB\BSON\ObjectId {#4896 +"oid": "5bc68aa8c5d851000161a575" }`
and some of them are saved as a regular string `_id: "5bb02547e710b95b3654cdf3"`. I realized for the ones that are stored as string I cannot do any modification to that document neither Save or Update works. Anyone has encountered this?

**Comment by irajtaghlidi** [comment]
Hi Hirad,

My first suggestion is explore your MongoDB with [MongoDB Compass](https://www.mongodb.com/products/compass) and check real type of document `_id` stored in Collection.

as your example ids you can check with these filters:
`{_id: ObjectId('5bc68aa8c5d851000161a575')}`

`{_id: '5bb02547e710b95b3654cdf3'}`

![screen shot 1397-09-19 at 00 30 02](https://user-images.githubusercontent.com/785830/49702855-c59fdf80-fc12-11e8-8209-9603b0cdf253.png)

if there are in different type, so you should check your create/save methods. 
what it your document creating methods?
Create Model or use fillable? 
and how about `_id` are you create them first or bring them to MongoDB? or do you use Bulk operation or just in Model Eloquent?

**Comment by aconital** [comment]
Thanks @irajtaghlidi. I'm closing this issue I don't think this problem has anything to do with this library. I had created some rows manually from my mongo admin page and I believe that was causing this problem

**Comment by tanmuhittin** [comment]
I am also having the same problem while saving subdocuments using methods:
https://github.com/jenssegers/laravel-mongodb#embedsmany-relations
https://github.com/jenssegers/laravel-mongodb#embedsone-relations


I found a solution. While saving subdocuments set _id field as new \MongoDB\BSON\ObjectId("_idhere") . Then they will all be saved as Object ids. This is an important issue because it breaks the consistency of real objects with the embedded ones. On save or update document method, we should look for all _id fields and replace them with new \MongoDB\BSON\ObjectId("_idhere").

Or maybe we should fix the behavior of saving embedded documents 
https://github.com/jenssegers/laravel-mongodb#embedsmany-relations
https://github.com/jenssegers/laravel-mongodb#embedsone-relations
