### ISSUE TITLE
New release 

### ISSUE THREAD

**Issue by Smolevich** [jenssegers/laravel-mongodb#1926]
I add to board accepted PR's that can include in new release 3.6.2
@rennokki , @Giacomo92 , @divine, @jenssegers i suggest to do it together

**Comment by Smolevich** [comment]
Board https://github.com/jenssegers/laravel-mongodb/projects/1

**Comment by divine** [comment]
Actually, that's a good idea, however I think we need to care for all PRs which can be updated and pushed back because some people haven't used github for some time and we can't wait for prime time.

See this for examples https://github.com/divine/laravel-mongodb/pull/3

Also, some PRs should be included in that release too https://github.com/jenssegers/laravel-mongodb/pull/1837 and etc.

Most requested/complained: https://github.com/jenssegers/laravel-mongodb/pull/1523

**Comment by Jannnnnn** [comment]
When is the next release expected? I would like to plan when I can upgrade to Laravel 6.

**Comment by divine** [comment]
> When is the next release expected? I would like to plan when I can upgrade to Laravel 6.

Hello,

I need to take care https://github.com/jenssegers/laravel-mongodb/pull/1796 , https://github.com/jenssegers/laravel-mongodb/pull/1745 , https://github.com/jenssegers/laravel-mongodb/pull/1854 

Most probably in the next 2 weeks, who knows, it takes time actually, if you can help we're happy.

**Comment by Jannnnnn** [comment]
> Hello,
> 
> I need to take care #1796 , #1745 , #1854
> 
> Most probably in the next 2 weeks, who knows, it takes time actually, if you can help we're happy.

Hello, thank you for your explanation, then I will wait. Unfortunately I am not that familiar with Eloquent and cannot help in deep. Maybe can't the mentioned issues published in a later release? Or are they dependent?

**Comment by divine** [comment]
> Hello, thank you for your explanation, then I will wait. Unfortunately I am not that familiar with Eloquent and cannot help in deep. Maybe can't the mentioned issues published in a later release? Or are they dependent?

Hello,

We need to clean up all PRs, because some of them are waiting for a few years ... that's actually sad.

We could probably release a new version now but please be patient and give us a time. 😃 

Thank you.
