### ISSUE TITLE
GridFS

### ISSUE THREAD

**Issue by jrvaja** [jenssegers/laravel-mongodb#262]
First of all, I would like to say thanks for such brilliant Lib for Laravel. I have used this API in my first MongoDB project and it works like charm. I request you to add feature of GridFD compatibility in this API.
I will be highly appreciate , if you can further assist me in this regards.

Cheers

**Comment by lenyapugachev** [comment]
Hello.

Not sure if it issue of this package, but I'm craving for your help.
I'm using multiple db connections and the main is mysql, so I'm trying to save file in GridFS like this:
```
$grid = DB::connection('mongo')->getMongoDB()->getGridFS();
$icon_file = $gridfs->storeFile($path);
```
But it's responding "Call to undefined method MongoDB\Database::getGridFS()". I did read #838, but I've checked phpinfo and pecl drivers mongo and mongodb are up to date.

So I'm stuck. Where should I dig now?

**Comment by lindelius** [comment]
Note: The `getGridFS()` function is no longer available in the new PHP MongoDB driver, which means that the code snippets above does not work if you have migrated to the new driver. In order to use GridFS with the new driver you will either have to import and use the `MongoDB\GridFS` classes from the official PHP library, or use the PHP driver classes directly.

**Comment by JoeyHoutenbos** [comment]
It is possible: https://github.com/jenssegers/laravel-mongodb/issues/826#issuecomment-290362789

**Comment by bisht2050** [comment]
GridFS is now supported! 
Follow the docs to learn how to use GridFS : https://www.mongodb.com/docs/drivers/php/laravel-mongodb/current/filesystems/
