### ISSUE TITLE
Error  Call to undefined method MongoDB\Database::connect().

### ISSUE THREAD

**Issue by batmahir** [jenssegers/laravel-mongodb#2649]
- Laravel-mongodb Version: 4.0
- PHP Version: 8.2
- Database Driver & Version: mongo 5

### Steps to reproduce
1. Run php artisan tinker with php8.2
2. run command : `DB::connect();`
3. Error will pop up

### Expected behaviour
It should be showing like connection success or failure instead of undefined method

### Actual behaviour
php artisan tinker
Psy Shell v0.11.21 (PHP 8.2.10 — cli) by Justin Hileman
> DB::connect();

   Error  Call to undefined method MongoDB\Database::connect().

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by hans-thomas** [comment]
I think this should answer your need.
```php
DB::connection()->getMongoClient()->listDatabaseNames()
```
If it connects successfully, it will return database names as `ArrayIterator`.
But if it fails, it will throw `MongoDB\Driver\Exception\ConnectionTimeoutException` exception.

**Comment by GromNaN** [comment]
Would you like to implement the `connect` function ? It seems to be in Eloquent.

**Comment by hans-thomas** [comment]
@GromNaN The `connect` method is declared [here](https://github.com/laravel/framework/blob/d9003667018a8546a3cffc140415506ce20988fe/src/Illuminate/Database/PDO/Concerns/ConnectsToDatabase.php#L22-L29) that used in [SQLiteDriver](https://github.com/laravel/framework/blob/10.x/src/Illuminate/Database/PDO/SQLiteDriver.php) class. The `SQLiteDriver` is registered in [SQLiteConnection](https://github.com/laravel/framework/blob/10.x/src/Illuminate/Database/SQLiteConnection.php) in a [protected getter method](https://github.com/laravel/framework/blob/d9003667018a8546a3cffc140415506ce20988fe/src/Illuminate/Database/SQLiteConnection.php#L130-L133). So, there is no way to call `connect`.
I can create a method on `MongoDB\Laravel\Connection` to check the connection using the given configs and name it `checkConnection` or something like this to check the connection status and return a `boolean` as the result. do you agree with this solution?

**Comment by alcaeus** [comment]
Before we do that, what's the use case for this? The driver manages connections automatically, and except for in special circumstances, the user shouldn't have to worry about them. Note that the driver doesn't allow closing the connection either, and unless you disable client persistence (which we don't recommend except for very special circumstances) even unsetting the client instance will not close the connection.

**Comment by jmikola** [comment]
@hans-thomas: regarding your solution in https://github.com/mongodb/laravel-mongodb/issues/2649#issuecomment-1777191042, listing database names goes beyond what's needed to ensure the driver actually connects, and in some environments that might also require special privileges on the authenticated user. The simplest approach would be to issue a `ping` command (`admin` database would be a fine choice). Alternatively, you can call [`Manager::selectServer()`](https://www.php.net/manual/en/mongodb-driver-manager.selectserver.php) since topology discovery is a precondition of server selection, and that will ensure the driver initializes its connections. When selecting a server, I'd also suggest using "primaryPreferred" instead of "primary" to avoid potential server selection failures if the primary was temporarily unavailable (assuming we only care about socket initialization here).

Per your other comment in https://github.com/mongodb/laravel-mongodb/issues/2649#issuecomment-1779195537, what is the relation to SQLiteDriver? Or were you just using that as an example of the [ConnectsToDatabase](https://github.com/laravel/framework/blob/d9003667018a8546a3cffc140415506ce20988fe/src/Illuminate/Database/PDO/Concerns/ConnectsToDatabase.php) trait?

**Comment by hans-thomas** [comment]
Thank you for your comment. I will give it a try later.

> Per your other comment in https://github.com/mongodb/laravel-mongodb/issues/2649#issuecomment-1779195537, what is the relation to SQLiteDriver? Or were you just using that as an example of the [ConnectsToDatabase](https://github.com/laravel/framework/blob/d9003667018a8546a3cffc140415506ce20988fe/src/Illuminate/Database/PDO/Concerns/ConnectsToDatabase.php) trait?

Nothing, I just wanted to clarify that there is no `connect` method publically available on `DB` facade. I used `SQLiteDriver` for example to check `connect` method availability.

**Comment by GromNaN** [comment]
Closing as [solutions to check the connection](https://github.com/mongodb/laravel-mongodb/issues/2649#issuecomment-1789354407) have been provided by @jmikola:

```php
use Illuminate\Support\Facades\DB;
use MongoDB\Driver\ReadPreference;
use MongoDB\Laravel\Connection;

DB::connection()->getMongoClient()->getManager()->selectServer(new ReadPreference(ReadPreference::PRIMARY_PREFERRED));
```

The method `Illuminate\Database\Connectors\ConnectorInterface::connect()` must return a `PDO` instance, which we can't do. So we will not implement this method.

**Comment by hans-thomas** [comment]
@GromNaN I think it's better to make a new `ping` method on `Connection` class to make it easy for users to access this feature.

**Comment by GromNaN** [comment]
That seems acceptable to me. Let’s do it.
