### ISSUE TITLE
Support / Best Practice question

### ISSUE THREAD

**Issue by lhilton** [jenssegers/laravel-mongodb#339]
This isn't a bug or issue with laravel-mongodb, but rather a best-practice style question for both the library and Mongo. I am used to using a pivot to handle belongsToMany relationships between a User and Role model. As the doc shows, laravel-mongodb doesn't use that pivot table but rather embeds the ID's in the record on both sides of the relationship.

With my use case of User and Model it is likely that records on Role side are going to become enormous over time. Will that cause performance issues for Mongo as that grows?

**Comment by askmatey** [comment]
This issue should be closed, since it is not a bug.

**Comment by hadikmsh** [comment]
Hi
Removing the pivot table leads to an unbounded array problem in some situations. Is there any option to use a pivot table in a many-to-many relationship? or any other solution for this problem?

**Comment by alcaeus** [comment]
There is no option to use a pivot table, and I'm currently struggling to see use-cases where bi-directional references that keep growing over time would become big enough to become an issue that doesn't point to a serious mistake in schema design. If you run into such a use case, please [create a discussion](https://github.com/mongodb/laravel-mongodb/discussions/new/choose) explaining your use case so we can discuss. Thank you!

**Comment by sloan58** [comment]
@alcaeus I'm just running into this challenge today and I'm curious about your take my situation.

I have ModelA which relates to ModelB through ModelE.  Each relationship type could potentially represent several hundred thousand records.  It's not growing over time, it's just a fact of the large environment and the number of objects that I'm storing.  In a traditional pivot table scenario each relationship would have their own table to store the many to many pairs.  In the case of MongoDB many to many, I will have one side of the relationship that I feel would certainly have the potential to run into scalability issues since it would be storing several hundred thousand array items for multiple relationships.

I'm working on an update to essentially create my own pivot table setup.  The flexibility of the MongoDB schema makes the extra effort completely worth it, but I think it would be nice to have an option to use pivot tables (collections) with MongoDB.  What do you think?  Thanks in advance.
