### ISSUE TITLE
ReplicaSet, and Files issue

### ISSUE THREAD

**Issue by mouradghafiri** [jenssegers/laravel-mongodb#385]
Hello,
First of all I really appreciate the effort you have spent working on this elegant ORM solution for MongoDB. also still wondering the intuition you reflect on the concepts you use.

It will be a pleasure of you could complete your library to support ReplicaSet because it is not working, I verified your source code so I find it is commented and not implemented nor tested yet.

also if you could help us dealing with persisting files easily that will really boost popularity of your library further.

Have a nice day,  and again I re-thank you for this package.

Best Regards;

**Comment by Seitk** [comment]
Hi, I came across and found your issue here. I just started to work with this library yesterday so correct me if I am wrong.

Based on the PHP driver document (http://php.net/manual/en/mongo.connecting.rs.php). The replicaSet option is passed as option when establishing the MongoClient connection.
```
// Sample code from php.net
$m = new MongoClient("mongodb://rs1.example.com:27017", array("replicaSet" => "myReplSetName"));
// Sample code from php.net END
```

Which is already done in this library Jenssegers\Mongodb\Connection@createConnection:133
I tried to dump the options and the replicaSet option is correctly set.
Here is my database configuration:

```
'mongodb' => array(
    'driver'   => 'mongodb',
    'host'     => array('localhost'),
    'username' => 'username',
    'password' => 'password',
    'database' => 'mongo-database',
    'options'  => array(
        'replicaSet' => 'replset-name',
        'readPreference' => MongoClient::RP_SECONDARY_PREFERRED
    )
),
```
