### ISSUE TITLE
Different ports on replicas

### ISSUE THREAD

**Issue by Vezul** [jenssegers/laravel-mongodb#413]
If your replicas uses different ports for each server, there is no way of specifying this right now.

As stated in the documentation:
```
'mongodb' => array(
    'driver'   => 'mongodb',
    'host'     => array('server1', 'server2'),
    'port'     => 27017,
    'username' => 'username',
    'password' => 'password',
    'database' => 'database',
    'options'  => array('replicaSet' => 'replicaSetName')
),
```

Instead I think you should be able to specific a port for each host, like so:

```
'mongodb' => array(
    'driver'   => 'mongodb',
    'host'     => array('server1', 'server2'),
    'port'     => array(27017, 27018),
    'username' => 'username',
    'password' => 'password',
    'database' => 'database',
    'options'  => array('replicaSet' => 'replicaSetName')
),
```
which should result in a path which respects the ports.

**Comment by nhalloran** [comment]
+1 for this. 

Seeing that compose.io uses a different port for each replica, I think it would be a common use case.

To nitpick -  allowing an array for port would work, but the relationship between the host and port field is not that intuitive.  For example, if there were 3 hosts and 2 port, what does that mean?  Still, other solutions I can think of would require coding something more elaborate.....

**Comment by nhalloran** [comment]
You know, this makes me appreciate the beauty of the good ol' connection string, that in my case, compose.io provided for my copy+paste pleasure.

It seems like in this library, this string ultimately gets generated from the config array here:
https://github.com/jenssegers/laravel-mongodb/blob/master/src/Jenssegers/Mongodb/Connection.php#L152-L174

So in my case, I deconstruct the connection string into an array which gets re-assembled into the original connection string - only it can't support the host-specific port. Is there an option to provide the original connection string instead of the array, to bypass all of this?

**Comment by jenssegers** [comment]
Will take this into consideration for the new version. Will probably apply the solution with an array of ports for each server.

**Comment by jenssegers** [comment]
You should be able to either pass a complete DSN or pass hosts including their ports now: `['localhost:27001', 'localhost:27002']`

**Comment by nhalloran** [comment]
Thanks so much J/S!  I just updated and it's working.
