### ISSUE TITLE
Relation getQualifiedParentKeyName is not protected anymore

### ISSUE THREAD

**Issue by juaniiton1** [jenssegers/laravel-mongodb#425]
With the new version of `"laravel/framework": "4.2.16"`, the method `getQualifiedParentKeyName` is now public, but in your library is still protected. So after update your dependencies it crashes for trying to rewrite it.

**Comment by ilesinge** [comment]
We experience the same issue.
The problem was resolved by this commit in 2.1.0beta:
https://github.com/jenssegers/laravel-mongodb/commit/76675fd7ee47f3c01737d268e64cae124aebe1e9
But 2.1.0beta is only compatible with Laravel 5.0.
As we need to maintain a project still using 4.2, it would be nice to have a 2.0.4 release of Laravel-MongoDB to fix this one issue.
Maybe it would be nice to create a 4.2 branch of Laravel-MongoDB for that kind of fix ?

**Comment by ilesinge** [comment]
By the way the change was introduced by Laravel 4.2.17, so it should be OK to use 4.2.16 against last stable version of Laravel-MongoDB

**Comment by jenssegers** [comment]
Guess I will have to create a 4.2 branch and update it?

**Comment by ilesinge** [comment]
That would be perfect!

**Comment by juaniiton1** [comment]
Yes, at the moment I've hardcoded the laravel version to 4.2.16, so it's working fine (until you add this little fix to a stable version).

**Comment by jenssegers** [comment]
Should be fixed in the new 2.0.4 release.
