### ISSUE TITLE
Debugbar query collector

### ISSUE THREAD

**Issue by DenchikBY** [jenssegers/laravel-mongodb#462]
Laravel 5. Don't launch event illuminate.query and dont show queries in debugbar. With mysql work.

**Comment by arcadas** [comment]
I had a same issue. I can't figured out what is the problem, so I created a new Service Provider and enable the query log in the boot method:

```php
// Debug bar - Queries
if ($config->get('app.debug')) {
    \DB::enableQueryLog();
}
```
Do you have a better solution?

**Comment by gidomanders** [comment]
That's because this plugin doesn't fully support L5 yet. #398

**Comment by DenchikBY** [comment]
@gidomanders it worked time ago in L5, but recently broke

**Comment by DenchikBY** [comment]
@arcadas thanks, it works, but not well... will wait updates

**Comment by lukepolo** [comment]
Thanks for that tip, it seems to work ok for me haven't had any issues!

**Comment by jenssegers** [comment]
If you want query logging, you need to enable it since it is disabled by default in Laravel 5.

**Comment by kroleg** [comment]
If you are using non-default connection named "mongodb" you'll need to add in your AppServiceProvider inside boot() method this code:
````php
\DB::connection('mongodb')->enableQueryLog();
````
Because \DB::enableQueryLog(); enables log only for 'default' database connection.
Hope that this comment will save couple of minutes for someone who tries to see what's going on in database :)

**Comment by adriantombu** [comment]
@kroleg you bet, thanks for your answer ! ( almost one year later, but who cares :beers:  )
