### ISSUE TITLE
Attribute type conversion issue

### ISSUE THREAD

**Issue by DaveyBoyCrocky** [jenssegers/laravel-mongodb#513]
Lets say I have an attribute that is an integer, for instance
$device = Device::find('my_key');
echo $device->userID; // outputs: 59
echo gettype($device->userID);   // outputs: integer

Now lets say that I want that attribute to be a string
$device->userID = "59";
$device->save();
echo gettype($device->userID);   // outputs: string

However it does not get saved in the database as a string.  It is determining that it was an integer and is (I guess) "helping you out" by converting it to an integer.  So after the above:

$device = Device::find('my_key');
echo gettype($device->userID);   // outputs: integer

To get it to save as a string, I needed to do this:
$device = Device::find('my_key');
$device->userID = "Goober";
$device->save();
$device->userID = "59";
$device->save();

Shouldn't a value be saved as a string if I set it to a string?

**Comment by cminatti** [comment]
The solution to this, is to override the method `originalIsEquivalent()` on your model. 
Replace the **last line** of that method (`return is_numeric($attribute) && is_numeric($original) && strcmp((string) $attribute, (string) $original) === 0;`) by `return false`; 
That laravel code, is done specifically to avoid modify an attribute which is equivalent, this is ok on mysql since the value will be stored with the type specified on the mysql table, but not in mongo where it will be stored as it is, integer or string. I don't know if  Jenssengers code has another solution and that is why he closed the issue, any comment is welcome.
