### ISSUE TITLE
How to Aggregate and count in collection?

### ISSUE THREAD

**Issue by julianoribero** [jenssegers/laravel-mongodb#535]
I need to run this.

db.mycollection.aggregate([{"$group" : {_id:{myalias:"$web_proxy_site"}, count:{$sum:1}}}])

How to implement this using jenssegers/laravel-mongodb package?

Thank you

**Comment by nahuelsgk** [comment]
Maybe this help you:
$result = \YOURMODEL::raw(function($collection) {
            return $collection->aggregate(
                [
                    '$group' => [
                        '_id'   => [
                            '_id' => '$web_proxy_site',
                        ]
                        'count' => [
                            '$sum' => 1
                        ]
                    ]
                ],
            );
        });

**Comment by julianoribero** [comment]
Thank you @nahuelsgk ....

**Comment by nishants93** [comment]
I'm already using
$data = Impression::raw()->aggregate(['$group'=>['_id'=>'$slug', 'count'=>['$sum'=>1]]]);
to find the result of aggregation query but I want to write the same using eloquent only so that i'm not dependent on DB
I tried
$data = Impression::groupBy('slug')->aggregate('count', ['slug'])->get(array('count'));
But not getting the desired result
I have worked a lot and tried dd($result) in Query/Builder.php class in getFresh() function
the result from this function seems to have the required data.
But I do not receive it in my controller, I think it is neglected somewhere in between.

Please help me in what i'm doing wrong.
