### ISSUE TITLE
can not find a id which type is integer

### ISSUE THREAD

**Issue by iyourplus** [jenssegers/laravel-mongodb#539]
I can not find id which type is integer using laravel-mongodb. But I can find id which type is integer using laravel-eloquent.

``` php
User::find($id)        // not found
User::find((int)$id)  // ok
```

```
{
    "_id": 1    // int, not string
}
```

**Comment by jenssegers** [comment]
I don't completely understand the problem, could you elaborate?

**Comment by iyourplus** [comment]
It can not find by id if the type of id is integer.
```
User::find($id)    // ok
{
    "_id": “4e7020cb7cac81af7136236b”
}
```
```
User::find($id)          // error
User::find((int)$id)     // ok, you must convert it to integer
{
    "_id": 1
}
```

**Comment by joepherh** [comment]
I've the same problem, I'm not using objectId as _id, I'm using integer 1, 2, 3, 4, 5 etc as _id and I cannot do something like User::where('_id', $id)->get(), better if User::where('id', (int)$id)->get(), totally fine if User::where('id', 1)->get()

**Comment by joepherh** [comment]
I've the same problem, I'm not using objectId as _id, I'm using integer 1, 2, 3, 4, 5 etc as _id and I cannot do something like User::where('_id', $id)->get(), better if User::where('id', (int)$id)->get(), totally fine if User::where('id', 1)->get()

**Comment by robsoncombr** [comment]
+1

And I can elaborate.

Forms come as strings from user interface, so for example a field called 'code' that is supposed to be int, comes as string and is saved as string into MongoDB.

This cause several problems:
a) you can not search correctly (if saved as int)
b) you can not order correctly (if saved as string)
c) you have problems to write custom Validators

You can convert the attribute to int before save, on Model:
public function setCodeAttribute($value) { $this->attributes['code'] = (int) $value; }

This solves the order problem, but causes the search issue reported on this.
We also find problems when using DB:: instead of Eloquent.

I was still not able to completely solve this, if someone find a solution please share.

**Comment by anthonypulido1984** [comment]
I think the issue that you all may be having, is that you need to type case it in both the query and the view. For example if you have a select option, type cast it as (int) in the option value. Then on the search query where condition also type cast it. I hope that helps anyone.
