### ISSUE TITLE
Nested eager loading wont load

### ISSUE THREAD

**Issue by darkeus** [jenssegers/laravel-mongodb#547]
@jenssegers i have a Model like this

Lesson -> Sublesson->Packets->Cases

Lesson embedsMany Sublesson
Sublesson embedsMany Packets
Packets HasMany Cases

now i do eager loading like this

```
Lessons::with(['sublessons','sublessons.packets','sublessons.packets.cases'])->get();
```

the only eagerLoaded Model is Sublesson, but nested wont load, i already check the source code, and the problem is on EmbedsOneOrMany.php on method getQuery(), the code has clone 

```
public function getQuery()
{
    // Because we are sharing this relation instance to models, we need
    // to make sure we use separate query instances.
    return clone $this->query;
}
```

why do you need to clone it? will it break if remove this, this why the nested eager loading wont be load because each time the getRelation method called, on the 

```
   $query->getQuery()->with($nested)
```

it wont set the Eloquent Builder eagerLoad property, instead in set on the cloned Eloquent Builder

```
    public function getRelation($relation)
{
    // We want to run a relationship query without any constrains so that we will
    // not have to remove these where clauses manually which gets really hacky
    // and is error prone while we remove the developer's own where clauses.
    $query = Relation::noConstraints(function() use ($relation)
    {
        return $this->getModel()->$relation();
    });

    $nested = $this->nestedRelations($relation);

    // If there are nested relationships set on the query, we will put those onto
    // the query instances so that they can be handled after this relationship
    // is loaded. In this way they will all trickle down as they are loaded.
    if (count($nested) > 0)
    {

        $query->getQuery()->with($nested);

    }

    return $query;
}
```

so i want to ask, what is the purpose of "clone $this->query;" in "EmbedsOneOrMany.php"

**Comment by hackel** [comment]
Eager loading makes no sense for embedded relations.  The data is already loaded from the original query, so it should just work.  You can't query just an embedded document by itself, that's why the original query for the parent document is cloned.

**Comment by JoeyHoutenbos** [comment]
Eager loading does makes sense for this issue: https://github.com/jenssegers/laravel-mongodb/issues/313

I also want to eager load nested relationships, but this is indeed not working =(

**Comment by JoeyHoutenbos** [comment]
A workaround for this problem is by defining a accessor in the Sublesson class.
You already have the embedsMany relation:

public function packets()
{
    return $this->embedsMany('Packet');
}

Define an accessor like this to solve the problem with the IDs:

public function getPacketsAttribute()
{
    return $this->packets;
}

**Comment by hackel** [comment]
@JoeyHoutenbos That seems entirely redundant, as the accessor will never get called.  $model->packets __calls \Jenssegers\Mongodb\Model::getAttribute(), which first checks for the existence of the packets() method on the model, and then returns the relationship.  It doesn't even check for get*Attribute methods unless the embedded relationship doesn't exist and it gets passed off to Eloquent's getAttribute().  Am I missing something?

I feel like there is some misunderstanding of what "eager loading" means.  It means querying the database for the related data in a model before it is accessed.  For embedded relationships, this happens automatically, every time, because there is only ever one database query to begin with.  That's why I said it makes no sense above.  Now, if you're talking about filling the model $relations property with the embedded model instances based on the attributes, that should be happening automatically on access, lazily.  This is fine, because you already have the data, which is the expensive operation, so there's no reason to "eagerly" create these instances if they aren't even going to be used.

**Comment by alexjose** [comment]
I have a belongsTo relationship inside the embedsMany. Now I want to eager load the belongsTo relationship using the nested relationship. How can I do that?

``` php
$establishment->load('locations.state') //locations is an embedsMany and state is a belongsTo in Location
```

**Comment by brentkozjak** [comment]
@alexjose I'm in exactly the same situation.  When trying to load a BelongsTo relationship inside an EmbedsMany, it doesn't work.

**Comment by sepisoltani** [comment]
> @alexjose I'm in exactly the same situation. When trying to load a BelongsTo relationship inside an EmbedsMany, it doesn't work.
@alexjose 


Simply you can define an append in Location model like below :

```
     protected $appends = ['state''];
```

Then define belongsTo relation in Location model

```
    public function state()
    {
        return $this->belongsTo(Location::class,'state_id');
    }

```
then define an accessor like this :

```

    public function getStateAttribute()
    {
        return $this->state;
    }

```
Now fetch them like below:


`$data =  BLOB::with(['locations','locations.state'])->get();
`

**Comment by omenomn** [comment]
That solution it's not eager load, that's make querie for each row like without eager loading.
