### ISSUE TITLE
Codeception cleanup

### ISSUE THREAD

**Issue by arall** [jenssegers/laravel-mongodb#550]
I'm getting an error if I run the database cleanup when I'm running my Unit tests:

```
PHP Fatal error:  Call to a member function beginTransaction() on null in /home/vagrant/code/personal/memento/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 498
```

I'm using version 2.1, Laravel 5.1, and Codeception 2.1 with Laravel5 module.

**Comment by Codestudios** [comment]
I have the same error, some answer ?

**Comment by AlaaAttyaMohamed** [comment]
i've the same error too

**Comment by deividaspetraitis** [comment]
Bump

**Comment by tzubertowski** [comment]
Shameless dump - this is because Codeception Laravel5 module runs all of the tests in [transaction](https://github.com/Codeception/Codeception/blob/2.4/src/Codeception/Module/Laravel5.php#L185) in order to roll them back each test. 
You can safely extend this Module and override _before method to disable the transaction triggering.
