### ISSUE TITLE
localhost:27017: Unknown modifier: updated_at

### ISSUE THREAD

**Issue by razzbee** [jenssegers/laravel-mongodb#653]
During update in eloquent , I get this error ,localhost:27017: Unknown modifier: updated_at , I dont know if its only me

**Comment by ajayideal** [comment]
Use where(array('_id'=>$id))->pull($update);

**Comment by erkanarslan** [comment]
I have the same problem. If you try to use MongoDB modifiers like $pull and $addToSet in update method, this error is created because Laraval MongoDB also tries to set "updated_at" field with these modifiers. As there is a key which doesn't start with $ sign in raw MongoDB update query, MongoDB creates an error.

**Comment by ElSamhaa** [comment]
Hello, Is there a proper way to do this on models? I'm facing the same issue when using `update`

**Comment by GromNaN** [comment]
@ElSamhaa please open an issue with a code sample that reproduces the error, so that we can investigate.
