### ISSUE TITLE
Update and save() not working for collection..

### ISSUE THREAD

**Issue by wissamk** [jenssegers/laravel-mongodb#655]
First of all, I'd like to thank Jens and the rest of the community for this incredible package.

Next, I stumbled on an issue that I can't seem to figure out:

I have a collection where _id is of type String. A requirement is to continue to use String as my datatype of choice for _id.
Retrieving documents is a bit of a pain, since I have to do:

$car = Car::where('_id', 'like', $id)->limit(1)->first();

Since Car::find($id) does not work for some reason.

Mainly however, I cant get this to work:

$car = Car::where('_id', 'like', $id)->first();
$car->title = 'new title';
$car->save();

Also, when creating a new document: Car::create($input), the _id are automatically casted to MongoId.

I have tried altering the mutator and accessors for _id, but doesn't do much. Also changed Model setAttribute, no improvements.

I am using Laravel 5.1 btw. New to Laravel in general.

Any pointers would be tremendously helpful. Thank you so much!

**Comment by always-beta** [comment]
I had same issue where find($id) doesn't work with primary key, and turned out that if _id is a string with length of 24, it will be converted to ObjectID object, which won't match the original 24 length string. Not sure if it's your case.

Now I have the same issue with the new attribute is not saved after call save(). Do you find out why?
