### ISSUE TITLE
Laravel 5.2

### ISSUE THREAD

**Issue by CWood1** [jenssegers/laravel-mongodb#694]
Are there any plans in place for a version supporting Laravel 5.2, and an approximate timeframe thereof?

**Comment by dgbrunoh** [comment]
Hi CWood1,

I don't know if helps, but I have a small application using Laravel 5.2 and this package and it's working fine until now.

Are you having any issues?

**Comment by CWood1** [comment]
I was mainly asking as, if not, I was going to take a look at starting the conversion, and wanted to avoid duplicate effort. If it tentitively works, I'll try on a larger application shortly, and report back here; if I find any issues, I'll start work on 5.2 support.

Thanks for reporting back!

**Comment by dgbrunoh** [comment]
Sounds Great ;)

**Comment by wuori** [comment]
The only issue I've had is with the Database Token Repository, which will throw an error anytime an Auth token is evaluated against it's expire date (e.g. when you click a change password email link). 

The problem is how they changed the service provider for 5.2 vs. 5.1 (https://github.com/laravel/framework/commit/1aa9577caf43fbcd769050d4c49f4af880991ef2#diff-ae1e33c0c665facb622cf6ce6187d5f1). I've been trying to create a workaround for this but haven't had too much time to figure out.

If you want to upgrade to 5.2, then in the meantime for a quick-fix, try replacing the code in `/vendor/laravel/framework/src/Illuminate/Auth/Passwords/DatabaseTokenRepository.php`, line 126 from:

    $expirationTime = strtotime($token['created_at']) + $this->expires;`

to 

    $expirationTime = strtotime($token['created_at']['date']) + $this->expires;

This will solve any password reset or token expires comparison issues, which are the only ones I've found so far and I've been using laravel-mongodb for both Eloquent and Query Builder on 5.2 quite a bit in the short time it's been released.

**Comment by bhargav3** [comment]
Thanks for mentioning the fix but I wouldn't be comfortable changing framework files as I need to sync this among different environments. Can we have a Laravel 5.2 release for this?

**Comment by zhaff** [comment]
Hi, I have same the problem as well using Laravel 5.2. I' m also not comfortable changing the framework files. Any thought?

**Comment by jenssegers** [comment]
Did you guys register the included `PasswordResetServiceProvider`? This should register a custom db repository.

**Comment by jenssegers** [comment]
Can you guys test out my last commit to the service provider?

**Comment by bhargav3** [comment]
Thanks @jenssegers I'll try and let you know

**Comment by zhaff** [comment]
@jenssegers Thank you for the fix. I just tested. The password reset worked perfectly now. Just that need to use Carbon to generate valid token's timestamp. Ref: https://github.com/zhaff/laravel-mongodb/commit/fb405cd92f3aadb31588410e91779cb47ae00980

**Comment by iceheat** [comment]
@jenssegers The latest commit breaks compatibility with Laravel 5.1 LTS. Illuminate\Auth\PasswordBrokerManager is only available in 5.2.

**Comment by bhargav3** [comment]
@jenssegers worked for me too. Thanks!

**Comment by jenssegers** [comment]
@iceheat are you getting an error? Seems to be working fine for me in 5.1 tests.

**Comment by iceheat** [comment]
@jenssegers yes, don't have the Class on my installation. Laravel api  shows its only available from 5.2. I only noticed the problem when I was attempting artisan route:list.

**Comment by Ravaelles** [comment]
iceheat is right, it broke my Laravel 5.1.30 project as well. I will upgrade to 5.2, I hope it solves the problem. But anyway, thanks for the mongo development, Jens!

**Comment by iceheat** [comment]
@Ravaelles a quick fix is to set your composer.json to require  "jenssegers/mongodb": "3.0.0-alpha" for now. Hope @jenssegers would figure a way around it soon

**Comment by lexx27** [comment]
I have the same issue with 5.2
