### ISSUE TITLE
Call to undefined method Jenssegers\Mongodb\Query\Builder::getHasCompareKey()

### ISSUE THREAD

**Issue by Lloople** [jenssegers/laravel-mongodb#730]
After doing `composer update` to have the fix for `wrap()` mentioned in #729 I'm getting this error:

> BadMethodCallException in Builder.php line 2093:
> Call to undefined method Jenssegers\Mongodb\Query\Builder::getHasCompareKey()

What I'm trying to do is this:

```
$query->whereHas('category', function($subq) use($search_term) {
                      $subq->where('title', 'like', '%'.$search_term.'%');
});
```

My current version is `v2.3.2`

**Comment by blackakula** [comment]
My little investigation mentioned in #729:

Implementation of `\Jenssegers\Mongodb\Eloquent\Builder::addHasWhere` has call to `$relation->getHasCompareKey()`, where `$relation` is instance of `\Jenssegers\Mongodb\Relations\BelongsTo`.

Take into account, that parent implementation of this method (`\Illuminate\Database\Eloquent\Builder::addHasWhere`) _doesn't_ have call to `getHasCompareKey` and that's why works.
So, it's still not possible to use `static::whereHas` like original one.

**Comment by manojnegii90** [comment]
any solution for this ?

**Comment by Kahfimaulana** [comment]
having the same issue, and still not finding the answer..

**Comment by webexpert4rv** [comment]
Same issue :(

**Comment by mean-cj** [comment]
yes i same.
