### ISSUE TITLE
How to load and call external javascript

### ISSUE THREAD

**Issue by mic1983** [jenssegers/laravel-mongodb#801]
Hi,
i have function.js file with this function
function addNumbers( x , y ) {
    return x + y;
}
i want to add it to mongo with load() function and then i want to execute this function and get result
I try with raw query but no working.

When i add it from mongo console 

> db.system.js.save({_id:"addNumbers", value:function(x, y){ return x + y; }});
> db.loadServerScripts();
> addNumbers(9,2);
> 11
> i see result. I want to do this from Laravel 5.2.

Please help.
Thanks!

**Comment by wuori** [comment]
What you're doing would probably be best achieved outside of Mongo altogether, and is not an issue specific to this library (laravel-mongodb) and therefore is not likely to be answered. 

However, to help you on your way, perhaps you want to revisit the idea of storing javascript inside of a database to start with. Either you want to execute this operation (adding two numbers) on the front-end, in which case your JS should already be available on the page or otherwise you're wanting to add these numbers on the store event, in which case you can use [an existing database function](https://docs.mongodb.org/manual/reference/operator/aggregation/add/#exp._S_add).

Additionally you may want to revisit the way Mongo is storing these values, particularly the _id, which should be a [MongoID Object](https://docs.mongodb.org/manual/reference/method/ObjectId/).

Again, this is not an issue specific to the library itself, so another forum (Stack Overflow, etc.) may be more helpful to you in your search for a solution.
