### ISSUE TITLE
addColumn causing issue on Forge with php 7

### ISSUE THREAD

**Issue by yespbs** [jenssegers/laravel-mongodb#823]
PHP Fatal error:  Access level to Jenssegers\Mongodb\Schema\Blueprint::addColumn() must be public (as in class Illuminate\Database\Schema\Blueprint) in /home/forge/default/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Schema/Blueprint.php on line 6

  [Symfony\Component\Debug\Exception\FatalErrorException]  
  Access level to Jenssegers\Mongodb\Schema\Blueprint::addColumn() must be pu  
  blic (as in class Illuminate\Database\Schema\Blueprint)

**Comment by DMarine68** [comment]
If you're running jenssegers 2.2.x there is a quick fix to it.  

Not sure if the problem came with Laravel or with Jenssegers, but you can modify the vendor file (not a standard practice I like doing): `/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Schema/Blueprint.php` on line 210.  Change `protected function addColumn($type, $name, array $parameters = [])` to `public function addColumn($type, $name, array $parameters = []) and you should be good to go.

**Comment by yespbs** [comment]
yes, I am just doing the same but for some time now, with each deploy, forge breaks it :(

I am using 3.0.0-beta since that works with php-7 and mongo 3.2 on our server
