### ISSUE TITLE
Is gridFS supported now?

### ISSUE THREAD

**Issue by steven-xian** [jenssegers/laravel-mongodb#838]
I tried the code just like said in [#231 ](https://github.com/jenssegers/laravel-mongodb/issues/231), but get error "call_user_func_array() expects parameter 1 to be a valid callback, class 'MongoDB\Database' does not have a method 'getGridFS'", I search entire help but cannot find description or example about GridFS, so anyone can give me some hints or help about how to use GridFS in latest version(v3.0.2)? thanks

here's my code, is anything wrong with them?
 I'm using laravel 5.2,
```
        $grid = DB::connection('mongodb')->getGridFS();
        $file_id = $grid->storeFile($file->getRealPath() );
        echo $file_id;
```

**Comment by steven-xian** [comment]
I used wrong mongo driver and download new version from https://s3.amazonaws.com/drivers.mongodb.org/php/index.html, It works fine.

**Comment by jmikola** [comment]
Version 3.0 of this library appears to wrap [mongodb/mongo-php-library](https://github.com/mongodb/mongo-php-library), which does not implement GridFS. Support for GridFS will show up in 1.1.0 (see: [PHPLIB-114](https://jira.mongodb.org/browse/PHPLIB-114)); however, it's API will differ significantly from the [legacy driver's GridFS API](http://php.net/mongogridfs).

**Comment by jmikola** [comment]
> how to use this package with gridfs, can show an example please

Answered in https://github.com/jenssegers/laravel-mongodb/issues/1596

**Comment by januzaq** [comment]
understand I need to extract the image from the database and display it on the browser, how can I do it can help or show, please

**Comment by januzaq** [comment]
I have here such code, which I extract the image from the database and try to display on the browser but something I do not so can help please

`public function show(){
        $test = DB::connection('mongodb4')->getMongoDB()->selectGridFSBucket(['bucketName' => 'files']);
        $id = new MongoDB\BSON\ObjectID('5b8fb2e5f5b4f23184005551');
        $stream = $test->openDownloadStream($id);
        while (!feof($stream)) {
            $photo = fread($stream, 8192);    
        }
 }   
        $type = 'png';
        $img = 'data:image/' . $type . ';base64,' . base64_encode($photo);
        return ("<img src='$img'>");`

**Comment by januzaq** [comment]
I have a ready mongodb gridfs database, it was used for ruby ​​on rails, and now I want to use laravel in the database, the name chunk_size is synchronized in this way, and in php it is used as chunkSize. How do I do this?

**Comment by jmikola** [comment]
[Downloading files with readable streams](https://docs.mongodb.com/php-library/current/tutorial/gridfs/#downloading-files-with-readable-streams) provides examples for obtaining the full contents of a GridFS file from a stream. The approach there is simpler than manually using `feof()` and `fread()` as you do above.

As for crafting the data URI, [Image Data URIs with PHP](https://davidwalsh.name/data-uri-php), [this gist](https://gist.github.com/hengkiardo/4023855), and [this Stack Overflow thread](https://stackoverflow.com/questions/12127751/php-output-datauri-base64-encode) may be helpful. This repository is likely not the appropriate forum for asking such a question (vs. Stack Overflow), since it falls outside the scope of the Laravel MongoDB library.

**Comment by bisht2050** [comment]
GridFS is now supported! 
Follow the docs to learn how to use GridFS : https://www.mongodb.com/docs/drivers/php/laravel-mongodb/current/filesystems/
