### ISSUE TITLE
not working with laravel scout elastic

### ISSUE THREAD

**Issue by harryy2510** [jenssegers/laravel-mongodb#962]
I am using Tamayo's laravel scout package for elasticsearch

https://github.com/ErickTamayo/laravel-scout-elastic/

On importing data through model, no mappings are created.
and search also doesnt gives any result
please help

**User Model**

`

```
protected $fillable = [
    'name', 'email', 'password',
];

protected $hidden = [
    'password', 'remember_token',
];

protected $dates = [
    'updated_at',
    'created_at'
];
```

`

**scout.php**

`

```
'driver' => env('SCOUT_DRIVER', 'elasticsearch'),

'prefix' => env('SCOUT_PREFIX', ''),


'queue' => false,

'elasticsearch' => [
    'index' => env('ELASTICSEARCH_INDEX', 'laravel'),
    'hosts' => [
        env('ELASTICSEARCH_HOST', 'http://192.168.10.10'),
    ],
],
```

`

**Comment by lukergz** [comment]
is there any workaround for this? I'm also having this problem in v5.4.19

**Comment by dannysood** [comment]
@lukergz  did you find a workaround?

**Comment by Surt** [comment]
I'm having the same issue, triying to "migrate" the data that I already have it gives me:

```
php artisan elastic:migrate App\Models\Content content
The index content was updated.
The content mapping was updated.
The content_write alias for the content index was deleted.
The content_write alias for the content index was created.

In Connection.php line 615:

  {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Field [_id] is a metadata field and cannot be added inside a document. Use the index API request parameters."}],"type":"mapper_parsing_exception","reason":
  "Field [_id] is a metadata field and cannot be added inside a document. Use the index API request parameters."},"status":400}

```

**Comment by kleytonroan** [comment]
To solve the "Field [_id] is a metadata field and cannot be added inside a document. [...]" error, i had to override toSearchableArray() method, put an $array['id'] = $array['_id'] and unset($array['_id']), this solved the isue. When you use embed Documents, you must do it too.

Someone could help me?
i have something like this:

`{
  "idFromCarModelOnMongo": "1",
  "make" : "Subaru",
  "model": "Imprezza"
  "products" : [
    {
      "make" : "John",
      "code" : "foo"
    },
    {
      "make" : "Jane",
      "code" : "bar"
    }
  ]
}`

I need to store in ES two documents, one insert with Subaru and foo document, and another with Subaru and bar document, because i'll search something like "Imprezza foo", and I need to get only the data about that specifc product, some one have any ideia? I'm using embedMany on MongoDB
