### ISSUE TITLE
Call to a member function all() on array

### ISSUE THREAD

**Issue by gp187** [jenssegers/laravel-mongodb#978]
Model:

``` php
use Jenssegers\Mongodb\Eloquent\Model as Moloquent;
class Product extends Moloquent
{
    protected $connection="mongodb";
    protected $dates = [
        'created_at', 'last_modified'
    ];
    protected $collection="products";
}
```

Controller:

``` php
class ProductCTRL extends Controller
{
    public function index(Request $request, $id)
    {
        $products = Product::where('cid', '=', $id)->get();
        return parent::formatResponse($products, true, 200);
    }
}
```

After running a `composer update`, gives out this error:

```
FatalThrowableError in Builder.php line 613:
Call to a member function all() on array
1. in Builder.php line 613
2. at Builder->getModels(array('*')) in Builder.php line 318
3. at Builder->get() in /srv/API/app/Http/Controllers/ProductCTRL.php line 44


```

_line `44` is where the `->get()` is_

If I do it like this, it works:

``` php
class ProductCTRL extends Controller
{
    public function index(Request $request, $id)
    {
        $db = DB::connection('mongodb')->collection("products");
        $products = $db->where('cid', '=', $id)->get();

        return parent::formatResponse($products, true, 200);
    }
}
```
- I have the latest version
- I reinstalled the plugin
- Still nothing

**Comment by pi0** [comment]
Would you provide your `composer.json` ?

**Comment by gp187** [comment]
Here it is
```json
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.6.4",
        "laravel/framework": "5.3.*",
        "jenssegers/mongodb": "^3.0",
        "guzzlehttp/guzzle": "^6.2",
        "predis/predis": "^1.1",
        "symfony/finder": "^3.1",
        "symfony/event-dispatcher": "2.8.9",
        "rocket-code/shopify": "^2.0"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~5.0",
        "symfony/css-selector": "3.1.*",
        "symfony/dom-crawler": "3.1.*",
        "laravel/homestead": "^3.0",
        "squizlabs/php_codesniffer": "^2.6"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php"
        ]
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-install-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postInstall",
            "php artisan optimize"
        ],
        "post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "php artisan optimize"
        ]
    },
    "config": {
        "preferred-install": "dist"
    }
}
```

**Comment by pi0** [comment]
@gp187 Latest version (which supports 5.3) is tagged as alpha so you have to explicitly change it to something like  this:
` "jenssegers/mongodb": "^3.1.0-alpha"`

**Comment by gp187** [comment]
Thanks @pi0 . Works now. I just thought the `^3` would pick up on latest.

**Comment by vrkansagara** [comment]
@gp187  and @pi0  works fine thanks  :+1:

**Comment by pongsakorn-playbasis** [comment]
Thanks @pi0  and @gp187. you saved my life

**Comment by jversmis** [comment]
It seems I can't get this to work.

When using dev-master branch, I get the error: `Call to a member function all() on array`

The error is thrown in `Illuminate\Database\Eloquent\Builder->getModels()`
This function is called by

```php 
return $query->get()->toArray();
```

where $query is an instance of `JensSegers\Mongodb\Eloquent\Builder`.

At the moment of writing, the getModels function looks like this:

```php
public function getModels($columns = ['*'])
{
    return $this->model->hydrate(
        $this->query->get($columns)->all(),
        $this->model->getConnectionName()
    )->all();
}
```

Since `$this->query->get($columns)` return an array, `$this->query->get($columns)->all()` throws the error `Call to a member function all() on array`

Removing the `->all()` from `$this->query->get($columns)->all()` fixes the issue.


When using a stable version (3.1.3 at the moment of writing), I run into [the non-public operators issue](https://github.com/jenssegers/laravel-mongodb/issues/1077).


Any ideas on how to solve this?

**Comment by mohitbhatia1994** [comment]
Same problem as @jversmis

**Comment by jversmis** [comment]
Back from holidays :-)

Some extra info, I'm using this package standalone.

The class `Jenssegers\Mongodb\Query\Builder` check in the constructor if it should use collections or not.
```
    /**
     * Returns true if Laravel or Lumen >= 5.3
     *
     * @return bool
     */
    protected function shouldUseCollections()
    {
        if (function_exists('app')) {
            $version = app()->version();
            $version = filter_var(explode(')', $version)[0], FILTER_SANITIZE_NUMBER_FLOAT, FILTER_FLAG_ALLOW_FRACTION); // lumen
            return version_compare($version, '5.3', '>=');
        }
    }
```

Since the `app` function doesn't exist, `shouldUseCollections` returns null and arrays are used. For testing, I've added `return true;` as the first line in the above function and running unit tests gives all green results again.

I don't have a solution yet. I suppose a dirty solution could be to create an app function in my project and have `app()->version();` return true. Not the prettiest solution but it would work for now.

**Comment by mohitbhatia1994** [comment]
@jversmis thanks for your input. would you mind telling me the right position to input the app() function. I am getting an syntax error when I included app function about shouldUseCollections.

**Comment by jversmis** [comment]
@mohitbhatia1994 

You can add the function anywhere in your project. Don't add it in the plugin code since any update of the plugin will erase the code again.

If you use any kind of framework, maybe you can add it in the bootstrap file. I've added it in a utils folder in the root of the project and load it through the autoload > file option in my composer.json

**Comment by mohitbhatia1994** [comment]
@jversmis understood. Still this line ``` return new class {``` giving a syntax error.

**Comment by jversmis** [comment]
@mohitbhatia1994 anonymous classes are a PHP 7 feature.

You can just use a named class, instantiate it and it should work.

For more info: http://php.net/manual/en/language.oop5.anonymous.php

**Comment by mohitbhatia1994** [comment]
@jversmis I am using php 5.6

**Comment by jversmis** [comment]
@mohitbhatia1994 in that case, just use a named class instead of an anonymous class

**Comment by mohitbhatia1994** [comment]
@jversmis Would you mind converting this to php5.6 as I tried but wasn't able to do it. 

`function app()
{
      return new class foo {
         public function version()
        {
            return '5.4';
        }
   }
}`

**Comment by jversmis** [comment]
@mohitbhatia1994 
Haven't tested it myself but that seems correct to me. Does it work?

**Comment by dyfire** [comment]
@mohitbhatia1994 u can do like this,

composer.json add

**Comment by lifeisgoodforall** [comment]
same error.
composer.json


{
    "require": {
        "maximebf/cachecache": "^1.0",  
        "erusev/parsedown": "^1.6", 
        "illuminate/database": "^5.2",
        "illuminate/events": "^5.2",
        "schnittstabil/csrf-tokenservice": "^1.0",
        "maximebf/debugbar": "^1.13", 
        "matthiasmullie/minify": "^1.3",
        "vlucas/valitron": "^1.4",
        "illuminate/pagination": "^5.2",
        "symfony/yaml": "^3.3",
        "rmccue/requests": "^1.7",
        "kamermans/docblock-reflection": "^1.0",
        "crada/php-apidoc": "^1.3",
        "overtrue/easy-sms": "^0.0.5",
        "jenssegers/mongodb": "^3.2" 
        
    },
    "autoload": {
    	    "classmap": ["./framework/"] ,
			"psr-4": { 
				"modules\\": "./modules/",
                "models\\": "./models/",
                "cs\\": "./class/" 
			}
	}
}

**Comment by elfeffe** [comment]
I have added this code just below my real class

```
class temp {
    public function version()
        {
            return '5.4';
        }
}

function app()
{
    return new temp();
};
```

And works good. I think it will also work if we use Database 5.3 instead of 5.4
